---
volumes:
  pgdata:

services:
  postgres:
    image: postgres:18-alpine
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data
