:showtitle:
:toc: left
:icons: font

= Lucid

Lucid is a server fleet management platform, designed to simplify the day to
day maintenance tasks of systems administrators.

Lucid provides inventory tracking, vulnerability alerting, compliance scanning
and more.

== Features

- [ ] Inventory host tracking
- [ ] Continuous compliance scanning
- [ ] Package vulnerability alerting

== Configuration

=== API Service

The Lucid API service can be configured via environment variables or command-line
flags.

==== Authentication & Signing

The API uses Ed25519 digital signatures for session token authentication. You
must provide a signing key for the API to start.

**Generate a signing key:**

[source,bash]
----
openssl genpkey -algorithm ED25519 -out signing_key.pem
----

**Configure the key** using one of these methods:

*Option 1: Environment variable (inline PEM)*

[source,bash]
----
export LUCID_API_SIGNING_KEY="-----BEGIN PRIVATE KEY-----
MC4CAQAwBQYDK2VwBCIEI...
-----END PRIVATE KEY-----"
----

*Option 2: Environment variable (file path)*

[source,bash]
----
export LUCID_API_SIGNING_KEY_FILE="/path/to/signing_key.pem"
----

*Option 3: Command-line flag*

[source,bash]
----
lucid-api --signing-key-file /path/to/signing_key.pem
----

IMPORTANT: Keep the signing key secure. Anyone with access to this key can forge
session tokens. Rotate keys regularly and never commit them to version control.
See link:./docs/SECURITY_ED25519.adoc[security considerations] for best practices.

TIP: Upgrading from a previous version? See link:./docs/MIGRATION_HMAC_TO_ED25519.adoc[the migration guide].

==== Other Configuration Options

[cols="2,3,2"]
|===
|Environment Variable |Description |Default

|`LUCID_API_BIND_ADDR`
|API server bind address
|`0.0.0.0:4000`

|`LUCID_API_PUBLIC_URL`
|Public-facing API URL (for redirects, links)
|`http://localhost:4000`

|`LUCID_API_MONGODB_URI`
|MongoDB connection string
|`mongodb://localhost:27017/lucid`
|===

== Help & Documentation

* https://roostmoe.github.io/lucid[Documentation] (Coming soon)
* Join https://matrix.to/#/#lucid:hayden.moe[`#lucid:hayden.moe`] on Matrix for
  help, support, or development discussions.

== Reporting an issue

If you believe you have found a bug in Lucid, please report it via a
https://github.com/roostmoe/lucid/issues/new/choose[GitHub Issue].

If you have a feature request, please also submit it via a GitHub Issue, but be
sure to label it as a feature request.

== Contributing

Before contributing to Lucid, please read our
link:./CONTRIBUTING.adoc[CONTRIBUTING] guidelines.

== Acknowledgements

* https://www.redhat.com/en/lightspeed[Red Hat Lightspeed], the initial
  inspiration for this project.

== License

This project is licensed under the Apache 2.0 license. See
link:./LICENSE[LICENSE] for more details.
