// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AuthLoginData, AuthLoginErrors, AuthLoginResponses, AuthLogoutData, AuthLogoutErrors, AuthLogoutResponses, AuthWhoamiData, AuthWhoamiErrors, AuthWhoamiResponses, GetHostData, GetHostErrors, GetHostResponses, ListHostsData, ListHostsErrors, ListHostsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const authLogin = <ThrowOnError extends boolean = false>(options: Options<AuthLoginData, ThrowOnError>) => (options.client ?? client).post<AuthLoginResponses, AuthLoginErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const authLogout = <ThrowOnError extends boolean = false>(options?: Options<AuthLogoutData, ThrowOnError>) => (options?.client ?? client).post<AuthLogoutResponses, AuthLogoutErrors, ThrowOnError>({ url: '/api/v1/auth/logout', ...options });

export const authWhoami = <ThrowOnError extends boolean = false>(options?: Options<AuthWhoamiData, ThrowOnError>) => (options?.client ?? client).get<AuthWhoamiResponses, AuthWhoamiErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/auth/me',
    ...options
});

export const listHosts = <ThrowOnError extends boolean = false>(options?: Options<ListHostsData, ThrowOnError>) => (options?.client ?? client).get<ListHostsResponses, ListHostsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/hosts',
    ...options
});

export const getHost = <ThrowOnError extends boolean = false>(options: Options<GetHostData, ThrowOnError>) => (options.client ?? client).get<GetHostResponses, GetHostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/hosts/{id}',
    ...options
});
