// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AuthLoginData, AuthLoginErrors, AuthLoginResponses, AuthLogoutData, AuthLogoutErrors, AuthLogoutResponses, AuthWhoamiData, AuthWhoamiErrors, AuthWhoamiResponses, CreateActivationKeyData, CreateActivationKeyErrors, CreateActivationKeyResponses, DeleteActivationKeyData, DeleteActivationKeyErrors, DeleteActivationKeyResponses, DeleteCaData, DeleteCaErrors, DeleteCaResponses, GenerateCaData, GenerateCaErrors, GenerateCaResponses, GetActivationKeyData, GetActivationKeyErrors, GetActivationKeyResponses, GetAgentWellKnownData, GetAgentWellKnownErrors, GetAgentWellKnownResponses, GetCaData, GetCaErrors, GetCaResponses, GetHostData, GetHostErrors, GetHostResponses, GetJwksData, GetJwksErrors, GetJwksResponses, GetOpenidConfigurationData, GetOpenidConfigurationErrors, GetOpenidConfigurationResponses, GetServerWellKnownData, GetServerWellKnownErrors, GetServerWellKnownResponses, ImportCaData, ImportCaErrors, ImportCaResponses, ListActivationKeysData, ListActivationKeysErrors, ListActivationKeysResponses, ListCasData, ListCasErrors, ListCasResponses, ListHostsData, ListHostsErrors, ListHostsResponses, RegisterAgentData, RegisterAgentErrors, RegisterAgentResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Retrieve the server's public JSON Web Key Set.
 *
 * Returns the Ed25519 public key(s) used by this server to sign tokens.
 * External services can use this endpoint to verify JWTs without needing
 * a shared secret.
 *
 * The key is represented as an OKP (Octet Key Pair) JWK per RFC 8037.
 *
 * # Example
 *
 * ```bash
 * curl http://localhost:4000/.well-known/jwks.json
 * ```
 *
 * ```json
 * {
 * "keys": [
 * {
 * "kty": "OKP",
 * "crv": "Ed25519",
 * "x": "11qYAYKxCrfVS_7TyWQHOg7hcvPapiMlrwIaaPcHURo",
 * "kid": "11qYAYKxCrfV",
 * "use": "sig",
 * "alg": "EdDSA"
 * }
 * ]
 * }
 * ```
 */
export const getJwks = <ThrowOnError extends boolean = false>(options?: Options<GetJwksData, ThrowOnError>) => (options?.client ?? client).get<GetJwksResponses, GetJwksErrors, ThrowOnError>({
    responseType: 'json',
    url: '/.well-known/jwks.json',
    ...options
});

/**
 * GET /.well-known/lucid/agent
 * Returns CA certificate information for agents.
 */
export const getAgentWellKnown = <ThrowOnError extends boolean = false>(options?: Options<GetAgentWellKnownData, ThrowOnError>) => (options?.client ?? client).get<GetAgentWellKnownResponses, GetAgentWellKnownErrors, ThrowOnError>({
    responseType: 'json',
    url: '/.well-known/lucid/agent',
    ...options
});

/**
 * GET /.well-known/lucid/agent
 * Returns CA certificate information for agents.
 */
export const getServerWellKnown = <ThrowOnError extends boolean = false>(options?: Options<GetServerWellKnownData, ThrowOnError>) => (options?.client ?? client).get<GetServerWellKnownResponses, GetServerWellKnownErrors, ThrowOnError>({
    responseType: 'json',
    url: '/.well-known/lucid/server',
    ...options
});

/**
 * OpenID Connect discovery endpoint.
 *
 * Returns minimal OIDC configuration needed for JWT verification.
 * Only includes `jwks_uri` pointing to the JWKS endpoint.
 *
 * # Example
 *
 * ```bash
 * curl http://localhost:4000/.well-known/openid-configuration
 * ```
 *
 * ```json
 * {
 * "jwks_uri": "http://localhost:4000/.well-known/jwks.json"
 * }
 * ```
 */
export const getOpenidConfiguration = <ThrowOnError extends boolean = false>(options?: Options<GetOpenidConfigurationData, ThrowOnError>) => (options?.client ?? client).get<GetOpenidConfigurationResponses, GetOpenidConfigurationErrors, ThrowOnError>({
    responseType: 'json',
    url: '/.well-known/openid-configuration',
    ...options
});

export const listActivationKeys = <ThrowOnError extends boolean = false>(options?: Options<ListActivationKeysData, ThrowOnError>) => (options?.client ?? client).get<ListActivationKeysResponses, ListActivationKeysErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/activation-keys',
    ...options
});

export const createActivationKey = <ThrowOnError extends boolean = false>(options: Options<CreateActivationKeyData, ThrowOnError>) => (options.client ?? client).post<CreateActivationKeyResponses, CreateActivationKeyErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/activation-keys',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteActivationKey = <ThrowOnError extends boolean = false>(options: Options<DeleteActivationKeyData, ThrowOnError>) => (options.client ?? client).delete<DeleteActivationKeyResponses, DeleteActivationKeyErrors, ThrowOnError>({ url: '/api/v1/activation-keys/{id}', ...options });

export const getActivationKey = <ThrowOnError extends boolean = false>(options: Options<GetActivationKeyData, ThrowOnError>) => (options.client ?? client).get<GetActivationKeyResponses, GetActivationKeyErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/activation-keys/{id}',
    ...options
});

/**
 * POST /api/v1/agents/register
 *
 * Register a new agent using an activation key JWT.
 */
export const registerAgent = <ThrowOnError extends boolean = false>(options: Options<RegisterAgentData, ThrowOnError>) => (options.client ?? client).post<RegisterAgentResponses, RegisterAgentErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/agents/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Authenticate user and create session.
 *
 * This endpoint validates user credentials and creates a new session stored in the database.
 * On success, it returns a session cookie and a CSRF token.
 *
 * # Flow
 *
 * 1. Validates username/password against database
 * 2. Generates unique session_id (ULID) and csrf_token (32 random chars)
 * 3. Creates session in database with 30-day TTL
 * 4. Signs session_id with Ed25519 key
 * 5. Returns signed token in `lucid_session` cookie + CSRF token in response body
 *
 * # Cookie Format
 *
 * - Name: `lucid_session`
 * - Value: `{session_id}.{ed25519_signature}`
 * - Flags: HttpOnly, SameSite=Lax, Path=/, Max-Age=2592000 (30 days)
 * - Secure: Only set when `public_url` starts with https://
 *
 * # CSRF Token
 *
 * The CSRF token must be stored by the client (e.g., in memory or localStorage) and sent
 * in the `X-CSRF-Token` header for all state-changing requests (POST, PUT, DELETE).
 *
 * # Example
 *
 * ```bash
 * curl -X POST http://localhost:3000/v1/auth/login \
 * -H "Content-Type: application/json" \
 * -d '{"username": "admin", "password": "secret"}' \
 * -c cookies.txt
 * ```
 *
 * # Errors
 *
 * - 401 Unauthorized: Invalid username or password
 * - 500 Internal Server Error: Database or signing failure
 */
export const authLogin = <ThrowOnError extends boolean = false>(options: Options<AuthLoginData, ThrowOnError>) => (options.client ?? client).post<AuthLoginResponses, AuthLoginErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * End the current session.
 *
 * This endpoint deletes the user's session from the database and clears the session cookie.
 * Requires both session cookie authentication AND the CSRF token.
 *
 * # Flow
 *
 * 1. Extracts and verifies session cookie from request
 * 2. Validates CSRF token (via Auth extractor)
 * 3. Deletes session from database
 * 4. Returns cookie with Max-Age=0 to clear it from browser
 *
 * # Security
 *
 * This is a state-changing operation, so it requires CSRF protection. The session cookie
 * alone is not sufficient - the CSRF token must also be provided.
 *
 * # Example
 *
 * ```bash
 * curl -X POST http://localhost:3000/v1/auth/logout \
 * -H "X-CSRF-Token: {csrf_token_from_login}" \
 * -b cookies.txt
 * ```
 *
 * # Errors
 *
 * - 401 Unauthorized: Missing or invalid session cookie
 * - 403 Forbidden: Invalid CSRF token
 * - 500 Internal Server Error: Database failure
 */
export const authLogout = <ThrowOnError extends boolean = false>(options?: Options<AuthLogoutData, ThrowOnError>) => (options?.client ?? client).post<AuthLogoutResponses, AuthLogoutErrors, ThrowOnError>({ url: '/api/v1/auth/logout', ...options });

/**
 * Get information about the authenticated user.
 *
 * Returns the current user's profile information including ID, username, display name,
 * and email. Requires session cookie authentication (no CSRF token needed for GET requests).
 *
 * # Example
 *
 * ```bash
 * curl http://localhost:3000/v1/auth/me \
 * -b cookies.txt
 * ```
 *
 * # Response
 *
 * ```json
 * {
 * "id": "user_object_id",
 * "username": "admin",
 * "display_name": "Administrator",
 * "email": "admin@example.com"
 * }
 * ```
 *
 * # Errors
 *
 * - 401 Unauthorized: Missing or invalid session cookie
 * - 404 Not Found: User no longer exists in database (stale session)
 * - 500 Internal Server Error: Database failure
 */
export const authWhoami = <ThrowOnError extends boolean = false>(options?: Options<AuthWhoamiData, ThrowOnError>) => (options?.client ?? client).get<AuthWhoamiResponses, AuthWhoamiErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/auth/me',
    ...options
});

export const listCas = <ThrowOnError extends boolean = false>(options?: Options<ListCasData, ThrowOnError>) => (options?.client ?? client).get<ListCasResponses, ListCasErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/cas',
    ...options
});

/**
 * Generate a new self-signed Ed25519 CA certificate and store it.
 */
export const generateCa = <ThrowOnError extends boolean = false>(options?: Options<GenerateCaData, ThrowOnError>) => (options?.client ?? client).post<GenerateCaResponses, GenerateCaErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/cas',
    ...options
});

/**
 * Import an existing CA certificate and private key.
 */
export const importCa = <ThrowOnError extends boolean = false>(options: Options<ImportCaData, ThrowOnError>) => (options.client ?? client).post<ImportCaResponses, ImportCaErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/cas/import',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteCa = <ThrowOnError extends boolean = false>(options: Options<DeleteCaData, ThrowOnError>) => (options.client ?? client).delete<DeleteCaResponses, DeleteCaErrors, ThrowOnError>({ url: '/api/v1/cas/{id}', ...options });

export const getCa = <ThrowOnError extends boolean = false>(options: Options<GetCaData, ThrowOnError>) => (options.client ?? client).get<GetCaResponses, GetCaErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/cas/{id}',
    ...options
});

export const listHosts = <ThrowOnError extends boolean = false>(options?: Options<ListHostsData, ThrowOnError>) => (options?.client ?? client).get<ListHostsResponses, ListHostsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/hosts',
    ...options
});

export const getHost = <ThrowOnError extends boolean = false>(options: Options<GetHostData, ThrowOnError>) => (options.client ?? client).get<GetHostResponses, GetHostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/hosts/{id}',
    ...options
});
