// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * An activation key used to bootstrap host agent configuration.
 */
export type ActivationKey = {
    /**
     * When the key was created
     */
    created_at: string;
    /**
     * Human-readable description
     */
    description: string;
    /**
     * Internal database ID
     */
    id: string;
    /**
     * User-provided key identifier
     */
    key_id: string;
};

export type AgentWellKnownResponse = {
    cas: Array<CaInfoResponse>;
    server_version: string;
};

/**
 * An error response for an API endpoint. This is used to return errors to the
 * client in a consistent format.
 */
export type ApiErrorResponse = {
    /**
     * An optional error code that can be used to identify the type of error
     * that occurred.
     */
    code?: string | null;
    details?: string | null;
    /**
     * A human-readable message describing the error that occurred.
     */
    message: string;
};

export type AuthLoginParams = {
    /**
     * The password of the user to authenticate as.
     */
    password: string;
    /**
     * The username or email of the user to authenticate as.
     */
    username: string;
};

/**
 * Response for the login endpoint.
 */
export type AuthLoginResponse = {
    /**
     * CSRF token that must be included in X-CSRF-Token header for mutating requests
     */
    csrf_token: string;
    token_type: 'Session';
} | {
    /**
     * The access token for the authenticated user.
     */
    access_token: string;
    /**
     * How long the token is valid for, in seconds. After this time has
     * elapsed, the user will need to use the refresh token to obtain a
     * new access token.
     */
    expires_in: number;
    /**
     * The refresh token for the user's new session.
     */
    refresh_token: string;
    token_type: 'Bearer';
};

/**
 * A certificate authority managed by Lucid.
 */
export type Ca = {
    /**
     * CA certificate in PEM format
     */
    cert_pem: string;
    /**
     * When this CA was created
     */
    created_at: string;
    /**
     * SHA-256 fingerprint of the certificate (format: `sha256:<hex>`)
     */
    fingerprint: string;
    /**
     * Internal database ID
     */
    id: string;
};

export type CaInfoResponse = {
    cert_pem: string;
    expires_at: string;
    fingerprint: string;
    issued_at: string;
};

/**
 * Request body for creating an activation key.
 */
export type CreateActivationKeyRequest = {
    /**
     * Human-readable description
     */
    description: string;
    /**
     * User-provided identifier for this key
     */
    key_id: string;
};

/**
 * Response for activation key creation - includes the JWT token.
 */
export type CreateActivationKeyResponse = {
    /**
     * The created activation key metadata
     */
    key: ActivationKey;
    /**
     * The JWT token - only returned on creation, store it securely!
     */
    token: string;
};

export type Host = {
    /**
     * The CPU architecture of the host, read from `uname -m`.
     */
    architecture: string;
    created_at: string;
    /**
     * Hostname of the machine. This is a human-readable identifier for the
     * host, and is not guaranteed to be unique.
     */
    hostname: string;
    /**
     * The unique identifier for this host.
     */
    id: string;
    /**
     * Network interfaces associated with this host. This is a one-to-many
     * relationship, as a host can have multiple network interfaces.
     */
    ifaces: Array<NetworkInterface>;
    last_seen_at: string;
    /**
     * The ID of the host's operating system, read from /etc/os-release.
     */
    os_id: string;
    /**
     * The name of the host's operating system, read from /etc/os-release.
     */
    os_name: string;
    /**
     * The version of the host's operating system, read from /etc/os-release.
     */
    os_version: string;
    updated_at: string;
};

/**
 * Request body for importing an existing certificate authority.
 */
export type ImportCaRequest = {
    /**
     * PEM-encoded CA certificate.
     */
    cert_pem: string;
    /**
     * PEM-encoded private key for the CA certificate (will be encrypted at
     * rest using the server's `LUCID_CA_ENCRYPTION_KEY`).
     */
    private_key_pem: string;
};

/**
 * A single JSON Web Key representing an OKP (Octet Key Pair) Ed25519 public key.
 */
export type Jwk = {
    /**
     * Algorithms this key supports — `"EdDSA"` for Ed25519.
     */
    alg: string;
    /**
     * Curve — always `"Ed25519"`.
     */
    crv: string;
    /**
     * Key ID — a base64url-encoded prefix of the public key bytes,
     * used to identify which key was used to sign a token.
     */
    kid: string;
    /**
     * Key type — always `"OKP"` for Ed25519 keys (RFC 8037).
     */
    kty: string;
    /**
     * Intended use of the key. `"sig"` indicates this key is for signing.
     */
    use: string;
    /**
     * Base64url-encoded public key bytes (32 bytes for Ed25519).
     */
    x: string;
};

/**
 * The JSON Web Key Set response, containing one or more public keys.
 */
export type JwkSet = {
    keys: Array<Jwk>;
};

export type NetworkInterface = {
    /**
     * The unique identifier for the host that this network interface is
     * associated with.
     */
    host_id?: string | null;
    /**
     * The unique identifier for this network interface.
     */
    id: string;
    /**
     * The name of the network interface.
     */
    iface: string;
    /**
     * The IP addresses associated with this network interface.
     */
    ip_addrs: Array<string>;
    /**
     * The state of the network interface. This can be "up", "down", or
     * "unknown".
     */
    state: NetworkInterfaceState;
};

export type NetworkInterfaceState = 'Up' | 'Down' | 'Unknown';

/**
 * OpenID Connect discovery response (minimal, for JWT verification only).
 */
export type OpenIdConfiguration = {
    /**
     * URL to the JWKS endpoint for retrieving public keys.
     */
    jwks_uri: string;
};

/**
 * Parameters for paginating through a list of records. This is used by the
 * various list endpoints to allow clients to paginate through large sets of
 * records.
 */
export type PaginatedListActivationKey = {
    items: Array<{
        /**
         * When the key was created
         */
        created_at: string;
        /**
         * Human-readable description
         */
        description: string;
        /**
         * Internal database ID
         */
        id: string;
        /**
         * User-provided key identifier
         */
        key_id: string;
    }>;
    /**
     * The maximum number of results to return.
     */
    limit?: number | null;
    /**
     * The next page token, if any. This is acquired by requesting a paginated
     * set of records and looking at the `next_token` or `prev_token` field.
     */
    next_token?: string | null;
};

/**
 * Parameters for paginating through a list of records. This is used by the
 * various list endpoints to allow clients to paginate through large sets of
 * records.
 */
export type PaginatedListCa = {
    items: Array<{
        /**
         * CA certificate in PEM format
         */
        cert_pem: string;
        /**
         * When this CA was created
         */
        created_at: string;
        /**
         * SHA-256 fingerprint of the certificate (format: `sha256:<hex>`)
         */
        fingerprint: string;
        /**
         * Internal database ID
         */
        id: string;
    }>;
    /**
     * The maximum number of results to return.
     */
    limit?: number | null;
    /**
     * The next page token, if any. This is acquired by requesting a paginated
     * set of records and looking at the `next_token` or `prev_token` field.
     */
    next_token?: string | null;
};

/**
 * Parameters for paginating through a list of records. This is used by the
 * various list endpoints to allow clients to paginate through large sets of
 * records.
 */
export type PaginatedListHost = {
    items: Array<{
        /**
         * The CPU architecture of the host, read from `uname -m`.
         */
        architecture: string;
        created_at: string;
        /**
         * Hostname of the machine. This is a human-readable identifier for the
         * host, and is not guaranteed to be unique.
         */
        hostname: string;
        /**
         * The unique identifier for this host.
         */
        id: string;
        /**
         * Network interfaces associated with this host. This is a one-to-many
         * relationship, as a host can have multiple network interfaces.
         */
        ifaces: Array<NetworkInterface>;
        last_seen_at: string;
        /**
         * The ID of the host's operating system, read from /etc/os-release.
         */
        os_id: string;
        /**
         * The name of the host's operating system, read from /etc/os-release.
         */
        os_name: string;
        /**
         * The version of the host's operating system, read from /etc/os-release.
         */
        os_version: string;
        updated_at: string;
    }>;
    /**
     * The maximum number of results to return.
     */
    limit?: number | null;
    /**
     * The next page token, if any. This is acquired by requesting a paginated
     * set of records and looking at the `next_token` or `prev_token` field.
     */
    next_token?: string | null;
};

export type RegisterAgentRequest = {
    /**
     * CSR in PEM format
     */
    csr_pem: string;
    /**
     * Hostname of the agent
     */
    hostname: string;
};

export type RegisterAgentResponse = {
    /**
     * Agent UUID (ObjectId as hex string)
     */
    agent_id: string;
    /**
     * API base URL for future requests
     */
    api_base_url: string;
    /**
     * CA certificate in PEM format
     */
    ca_certificate_pem: string;
    /**
     * Signed certificate in PEM format
     */
    certificate_pem: string;
    /**
     * Certificate expiration time
     */
    expires_at: string;
};

export type User = {
    created_at: string;
    /**
     * The user's display name.
     */
    display_name: string;
    /**
     * The user's email address.
     */
    email: string;
    /**
     * The unique identifier for this user.
     */
    id: string;
    updated_at: string;
};

export type GetJwksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/.well-known/jwks.json';
};

export type GetJwksErrors = {
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    400: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    401: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    403: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    404: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    500: unknown;
};

export type GetJwksResponses = {
    /**
     * JSON Web Key Set
     */
    200: JwkSet;
};

export type GetJwksResponse = GetJwksResponses[keyof GetJwksResponses];

export type GetAgentWellKnownData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/.well-known/lucid/agent';
};

export type GetAgentWellKnownErrors = {
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    400: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    401: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    403: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    404: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    500: unknown;
    /**
     * CA not initialized
     */
    503: unknown;
};

export type GetAgentWellKnownResponses = {
    /**
     * Agent configuration
     */
    200: AgentWellKnownResponse;
};

export type GetAgentWellKnownResponse = GetAgentWellKnownResponses[keyof GetAgentWellKnownResponses];

export type GetServerWellKnownData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/.well-known/lucid/server';
};

export type GetServerWellKnownErrors = {
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    400: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    401: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    403: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    404: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    500: unknown;
};

export type GetServerWellKnownResponses = {
    /**
     * Server configuration
     */
    200: AgentWellKnownResponse;
};

export type GetServerWellKnownResponse = GetServerWellKnownResponses[keyof GetServerWellKnownResponses];

export type GetOpenidConfigurationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/.well-known/openid-configuration';
};

export type GetOpenidConfigurationErrors = {
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    400: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    401: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    403: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    404: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    500: unknown;
};

export type GetOpenidConfigurationResponses = {
    /**
     * OpenID Connect discovery document
     */
    200: OpenIdConfiguration;
};

export type GetOpenidConfigurationResponse = GetOpenidConfigurationResponses[keyof GetOpenidConfigurationResponses];

export type ListActivationKeysData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/activation-keys';
};

export type ListActivationKeysErrors = {
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    400: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    401: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    403: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    404: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    500: unknown;
};

export type ListActivationKeysResponses = {
    /**
     * List of activation keys
     */
    200: PaginatedListActivationKey;
};

export type ListActivationKeysResponse = ListActivationKeysResponses[keyof ListActivationKeysResponses];

export type CreateActivationKeyData = {
    body: CreateActivationKeyRequest;
    path?: never;
    query?: never;
    url: '/api/v1/activation-keys';
};

export type CreateActivationKeyErrors = {
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    400: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    401: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    403: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    404: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    500: unknown;
};

export type CreateActivationKeyResponses = {
    /**
     * Activation key created
     */
    201: CreateActivationKeyResponse;
};

export type CreateActivationKeyResponse2 = CreateActivationKeyResponses[keyof CreateActivationKeyResponses];

export type DeleteActivationKeyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/activation-keys/{id}';
};

export type DeleteActivationKeyErrors = {
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    400: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    401: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    403: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    404: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    500: unknown;
};

export type DeleteActivationKeyResponses = {
    /**
     * Activation key deleted
     */
    204: void;
};

export type DeleteActivationKeyResponse = DeleteActivationKeyResponses[keyof DeleteActivationKeyResponses];

export type GetActivationKeyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/activation-keys/{id}';
};

export type GetActivationKeyErrors = {
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    400: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    401: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    403: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    404: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    500: unknown;
};

export type GetActivationKeyResponses = {
    /**
     * Activation key details
     */
    200: ActivationKey;
};

export type GetActivationKeyResponse = GetActivationKeyResponses[keyof GetActivationKeyResponses];

export type RegisterAgentData = {
    body: RegisterAgentRequest;
    path?: never;
    query?: never;
    url: '/api/v1/agents/register';
};

export type RegisterAgentErrors = {
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    400: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    401: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    403: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    404: unknown;
    /**
     * Activation key already used
     */
    409: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    500: unknown;
    /**
     * CA not initialized
     */
    503: unknown;
};

export type RegisterAgentResponses = {
    /**
     * Agent registered successfully
     */
    200: RegisterAgentResponse;
};

export type RegisterAgentResponse2 = RegisterAgentResponses[keyof RegisterAgentResponses];

export type AuthLoginData = {
    body: AuthLoginParams;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type AuthLoginErrors = {
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    400: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    401: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    403: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    404: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    500: unknown;
};

export type AuthLoginResponses = {
    /**
     * Successful login
     */
    201: AuthLoginResponse;
};

export type AuthLoginResponse2 = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type AuthLogoutErrors = {
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    400: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    401: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    403: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    404: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    500: unknown;
};

export type AuthLogoutResponses = {
    /**
     * Successful logout
     */
    200: unknown;
};

export type AuthWhoamiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type AuthWhoamiErrors = {
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    400: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    401: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    403: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    404: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    500: unknown;
};

export type AuthWhoamiResponses = {
    /**
     * User information
     */
    200: User;
};

export type AuthWhoamiResponse = AuthWhoamiResponses[keyof AuthWhoamiResponses];

export type ListCasData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/cas';
};

export type ListCasErrors = {
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    400: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    401: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    403: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    404: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    500: unknown;
};

export type ListCasResponses = {
    /**
     * List of certificate authorities
     */
    200: PaginatedListCa;
};

export type ListCasResponse = ListCasResponses[keyof ListCasResponses];

export type GenerateCaData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/cas';
};

export type GenerateCaErrors = {
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    400: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    401: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    403: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    404: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    500: unknown;
};

export type GenerateCaResponses = {
    /**
     * Certificate authority generated
     */
    201: Ca;
};

export type GenerateCaResponse = GenerateCaResponses[keyof GenerateCaResponses];

export type ImportCaData = {
    body: ImportCaRequest;
    path?: never;
    query?: never;
    url: '/api/v1/cas/import';
};

export type ImportCaErrors = {
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    400: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    401: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    403: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    404: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    500: unknown;
};

export type ImportCaResponses = {
    /**
     * Certificate authority imported
     */
    201: Ca;
};

export type ImportCaResponse = ImportCaResponses[keyof ImportCaResponses];

export type DeleteCaData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/cas/{id}';
};

export type DeleteCaErrors = {
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    400: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    401: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    403: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    404: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    500: unknown;
};

export type DeleteCaResponses = {
    /**
     * Certificate authority deleted
     */
    204: void;
};

export type DeleteCaResponse = DeleteCaResponses[keyof DeleteCaResponses];

export type GetCaData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/cas/{id}';
};

export type GetCaErrors = {
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    400: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    401: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    403: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    404: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    500: unknown;
};

export type GetCaResponses = {
    /**
     * Certificate authority details
     */
    200: Ca;
};

export type GetCaResponse = GetCaResponses[keyof GetCaResponses];

export type ListHostsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/hosts';
};

export type ListHostsErrors = {
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    400: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    401: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    403: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    404: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    500: unknown;
};

export type ListHostsResponses = {
    /**
     * List of hosts
     */
    200: PaginatedListHost;
};

export type ListHostsResponse = ListHostsResponses[keyof ListHostsResponses];

export type GetHostData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/hosts/{id}';
};

export type GetHostErrors = {
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    400: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    401: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    403: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    404: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    500: unknown;
};

export type GetHostResponses = {
    /**
     * Resolved host
     */
    200: Host;
};

export type GetHostResponse = GetHostResponses[keyof GetHostResponses];
