// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * An error response for an API endpoint. This is used to return errors to the
 * client in a consistent format.
 */
export type ApiErrorResponse = {
    /**
     * An optional error code that can be used to identify the type of error
     * that occurred.
     */
    code?: string | null;
    details?: string | null;
    /**
     * A human-readable message describing the error that occurred.
     */
    message: string;
};

export type AuthLoginParams = {
    /**
     * The password of the user to authenticate as.
     */
    password: string;
    /**
     * The username or email of the user to authenticate as.
     */
    username: string;
};

/**
 * Response for the login endpoint.
 */
export type AuthLoginResponse = {
    /**
     * CSRF token that must be included in X-CSRF-Token header for mutating requests
     */
    csrf_token: string;
    token_type: 'Session';
} | {
    /**
     * The access token for the authenticated user.
     */
    access_token: string;
    /**
     * How long the token is valid for, in seconds. After this time has
     * elapsed, the user will need to use the refresh token to obtain a
     * new access token.
     */
    expires_in: number;
    /**
     * The refresh token for the user's new session.
     */
    refresh_token: string;
    token_type: 'Bearer';
};

export type Host = {
    created_at: string;
    /**
     * Hostname of the machine. This is a human-readable identifier for the
     * host, and is not guaranteed to be unique.
     */
    hostname: string;
    /**
     * The unique identifier for this host.
     */
    id: string;
    /**
     * Network interfaces associated with this host. This is a one-to-many
     * relationship, as a host can have multiple network interfaces.
     */
    ifaces: Array<NetworkInterface>;
    updated_at: string;
};

export type NetworkInterface = {
    /**
     * The unique identifier for the host that this network interface is
     * associated with.
     */
    host_id?: string | null;
    /**
     * The unique identifier for this network interface.
     */
    id: string;
    /**
     * The name of the network interface.
     */
    iface: string;
    /**
     * The IP addresses associated with this network interface.
     */
    ip_addrs: Array<string>;
    /**
     * The state of the network interface. This can be "up", "down", or
     * "unknown".
     */
    state: NetworkInterfaceState;
};

export type NetworkInterfaceState = 'Up' | 'Down' | 'Unknown';

/**
 * Parameters for paginating through a list of records. This is used by the
 * various list endpoints to allow clients to paginate through large sets of
 * records.
 */
export type PaginatedListHost = {
    items: Array<{
        created_at: string;
        /**
         * Hostname of the machine. This is a human-readable identifier for the
         * host, and is not guaranteed to be unique.
         */
        hostname: string;
        /**
         * The unique identifier for this host.
         */
        id: string;
        /**
         * Network interfaces associated with this host. This is a one-to-many
         * relationship, as a host can have multiple network interfaces.
         */
        ifaces: Array<NetworkInterface>;
        updated_at: string;
    }>;
    /**
     * The maximum number of results to return.
     */
    limit?: number | null;
    /**
     * The next page token, if any. This is acquired by requesting a paginated
     * set of records and looking at the `next_token` or `prev_token` field.
     */
    next_token?: string | null;
};

export type User = {
    created_at: string;
    /**
     * The user's display name.
     */
    display_name: string;
    /**
     * The user's email address.
     */
    email: string;
    /**
     * The unique identifier for this user.
     */
    id: string;
    updated_at: string;
};

export type AuthLoginData = {
    body: AuthLoginParams;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type AuthLoginErrors = {
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    400: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    401: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    403: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    404: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    500: unknown;
};

export type AuthLoginResponses = {
    /**
     * Successful login
     */
    201: AuthLoginResponse;
};

export type AuthLoginResponse2 = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type AuthLogoutErrors = {
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    400: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    401: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    403: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    404: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    500: unknown;
};

export type AuthLogoutResponses = {
    /**
     * Successful logout
     */
    200: unknown;
};

export type AuthWhoamiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type AuthWhoamiErrors = {
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    400: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    401: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    403: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    404: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    500: unknown;
};

export type AuthWhoamiResponses = {
    /**
     * User information
     */
    200: User;
};

export type AuthWhoamiResponse = AuthWhoamiResponses[keyof AuthWhoamiResponses];

export type ListHostsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/hosts';
};

export type ListHostsErrors = {
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    400: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    401: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    403: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    404: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    500: unknown;
};

export type ListHostsResponses = {
    /**
     * List of hosts
     */
    200: PaginatedListHost;
};

export type ListHostsResponse = ListHostsResponses[keyof ListHostsResponses];

export type GetHostData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/hosts/{id}';
};

export type GetHostErrors = {
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    400: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    401: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    403: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    404: unknown;
    /**
     * An error response for an API endpoint. This is used to return errors to the
     * client in a consistent format.
     */
    500: unknown;
};

export type GetHostResponses = {
    /**
     * Resolved host
     */
    200: Host;
};

export type GetHostResponse = GetHostResponses[keyof GetHostResponses];
