// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { authLogin, authLogout, authWhoami, createActivationKey, deleteActivationKey, deleteCa, generateCa, getActivationKey, getAgentWellKnown, getCa, getHost, getJwks, getOpenidConfiguration, getServerWellKnown, importCa, listActivationKeys, listCas, listHosts, type Options, registerAgent } from '../sdk.gen';
import type { AuthLoginData, AuthLoginResponse2, AuthLogoutData, AuthWhoamiData, AuthWhoamiResponse, CreateActivationKeyData, CreateActivationKeyResponse2, DeleteActivationKeyData, DeleteActivationKeyResponse, DeleteCaData, DeleteCaResponse, GenerateCaData, GenerateCaResponse, GetActivationKeyData, GetActivationKeyResponse, GetAgentWellKnownData, GetAgentWellKnownResponse, GetCaData, GetCaResponse, GetHostData, GetHostResponse, GetJwksData, GetJwksResponse, GetOpenidConfigurationData, GetOpenidConfigurationResponse, GetServerWellKnownData, GetServerWellKnownResponse, ImportCaData, ImportCaResponse, ListActivationKeysData, ListActivationKeysResponse, ListCasData, ListCasResponse, ListHostsData, ListHostsResponse, RegisterAgentData, RegisterAgentResponse2 } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getJwksQueryKey = (options?: Options<GetJwksData>) => createQueryKey('getJwks', options);

/**
 * Retrieve the server's public JSON Web Key Set.
 *
 * Returns the Ed25519 public key(s) used by this server to sign tokens.
 * External services can use this endpoint to verify JWTs without needing
 * a shared secret.
 *
 * The key is represented as an OKP (Octet Key Pair) JWK per RFC 8037.
 *
 * # Example
 *
 * ```bash
 * curl http://localhost:4000/.well-known/jwks.json
 * ```
 *
 * ```json
 * {
 * "keys": [
 * {
 * "kty": "OKP",
 * "crv": "Ed25519",
 * "x": "11qYAYKxCrfVS_7TyWQHOg7hcvPapiMlrwIaaPcHURo",
 * "kid": "11qYAYKxCrfV",
 * "use": "sig",
 * "alg": "EdDSA"
 * }
 * ]
 * }
 * ```
 */
export const getJwksOptions = (options?: Options<GetJwksData>) => queryOptions<GetJwksResponse, AxiosError<DefaultError>, GetJwksResponse, ReturnType<typeof getJwksQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getJwks({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getJwksQueryKey(options)
});

export const getAgentWellKnownQueryKey = (options?: Options<GetAgentWellKnownData>) => createQueryKey('getAgentWellKnown', options);

/**
 * GET /.well-known/lucid/agent
 * Returns CA certificate information for agents.
 */
export const getAgentWellKnownOptions = (options?: Options<GetAgentWellKnownData>) => queryOptions<GetAgentWellKnownResponse, AxiosError<DefaultError>, GetAgentWellKnownResponse, ReturnType<typeof getAgentWellKnownQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAgentWellKnown({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAgentWellKnownQueryKey(options)
});

export const getServerWellKnownQueryKey = (options?: Options<GetServerWellKnownData>) => createQueryKey('getServerWellKnown', options);

/**
 * GET /.well-known/lucid/agent
 * Returns CA certificate information for agents.
 */
export const getServerWellKnownOptions = (options?: Options<GetServerWellKnownData>) => queryOptions<GetServerWellKnownResponse, AxiosError<DefaultError>, GetServerWellKnownResponse, ReturnType<typeof getServerWellKnownQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getServerWellKnown({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getServerWellKnownQueryKey(options)
});

export const getOpenidConfigurationQueryKey = (options?: Options<GetOpenidConfigurationData>) => createQueryKey('getOpenidConfiguration', options);

/**
 * OpenID Connect discovery endpoint.
 *
 * Returns minimal OIDC configuration needed for JWT verification.
 * Only includes `jwks_uri` pointing to the JWKS endpoint.
 *
 * # Example
 *
 * ```bash
 * curl http://localhost:4000/.well-known/openid-configuration
 * ```
 *
 * ```json
 * {
 * "jwks_uri": "http://localhost:4000/.well-known/jwks.json"
 * }
 * ```
 */
export const getOpenidConfigurationOptions = (options?: Options<GetOpenidConfigurationData>) => queryOptions<GetOpenidConfigurationResponse, AxiosError<DefaultError>, GetOpenidConfigurationResponse, ReturnType<typeof getOpenidConfigurationQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getOpenidConfiguration({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getOpenidConfigurationQueryKey(options)
});

export const listActivationKeysQueryKey = (options?: Options<ListActivationKeysData>) => createQueryKey('listActivationKeys', options);

export const listActivationKeysOptions = (options?: Options<ListActivationKeysData>) => queryOptions<ListActivationKeysResponse, AxiosError<DefaultError>, ListActivationKeysResponse, ReturnType<typeof listActivationKeysQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listActivationKeys({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listActivationKeysQueryKey(options)
});

export const createActivationKeyMutation = (options?: Partial<Options<CreateActivationKeyData>>): UseMutationOptions<CreateActivationKeyResponse2, AxiosError<DefaultError>, Options<CreateActivationKeyData>> => {
    const mutationOptions: UseMutationOptions<CreateActivationKeyResponse2, AxiosError<DefaultError>, Options<CreateActivationKeyData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createActivationKey({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteActivationKeyMutation = (options?: Partial<Options<DeleteActivationKeyData>>): UseMutationOptions<DeleteActivationKeyResponse, AxiosError<DefaultError>, Options<DeleteActivationKeyData>> => {
    const mutationOptions: UseMutationOptions<DeleteActivationKeyResponse, AxiosError<DefaultError>, Options<DeleteActivationKeyData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteActivationKey({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getActivationKeyQueryKey = (options: Options<GetActivationKeyData>) => createQueryKey('getActivationKey', options);

export const getActivationKeyOptions = (options: Options<GetActivationKeyData>) => queryOptions<GetActivationKeyResponse, AxiosError<DefaultError>, GetActivationKeyResponse, ReturnType<typeof getActivationKeyQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getActivationKey({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getActivationKeyQueryKey(options)
});

/**
 * POST /api/v1/agents/register
 *
 * Register a new agent using an activation key JWT.
 */
export const registerAgentMutation = (options?: Partial<Options<RegisterAgentData>>): UseMutationOptions<RegisterAgentResponse2, AxiosError<DefaultError>, Options<RegisterAgentData>> => {
    const mutationOptions: UseMutationOptions<RegisterAgentResponse2, AxiosError<DefaultError>, Options<RegisterAgentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await registerAgent({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Authenticate user and create session.
 *
 * This endpoint validates user credentials and creates a new session stored in the database.
 * On success, it returns a session cookie and a CSRF token.
 *
 * # Flow
 *
 * 1. Validates username/password against database
 * 2. Generates unique session_id (ULID) and csrf_token (32 random chars)
 * 3. Creates session in database with 30-day TTL
 * 4. Signs session_id with Ed25519 key
 * 5. Returns signed token in `lucid_session` cookie + CSRF token in response body
 *
 * # Cookie Format
 *
 * - Name: `lucid_session`
 * - Value: `{session_id}.{ed25519_signature}`
 * - Flags: HttpOnly, SameSite=Lax, Path=/, Max-Age=2592000 (30 days)
 * - Secure: Only set when `public_url` starts with https://
 *
 * # CSRF Token
 *
 * The CSRF token must be stored by the client (e.g., in memory or localStorage) and sent
 * in the `X-CSRF-Token` header for all state-changing requests (POST, PUT, DELETE).
 *
 * # Example
 *
 * ```bash
 * curl -X POST http://localhost:3000/v1/auth/login \
 * -H "Content-Type: application/json" \
 * -d '{"username": "admin", "password": "secret"}' \
 * -c cookies.txt
 * ```
 *
 * # Errors
 *
 * - 401 Unauthorized: Invalid username or password
 * - 500 Internal Server Error: Database or signing failure
 */
export const authLoginMutation = (options?: Partial<Options<AuthLoginData>>): UseMutationOptions<AuthLoginResponse2, AxiosError<DefaultError>, Options<AuthLoginData>> => {
    const mutationOptions: UseMutationOptions<AuthLoginResponse2, AxiosError<DefaultError>, Options<AuthLoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authLogin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * End the current session.
 *
 * This endpoint deletes the user's session from the database and clears the session cookie.
 * Requires both session cookie authentication AND the CSRF token.
 *
 * # Flow
 *
 * 1. Extracts and verifies session cookie from request
 * 2. Validates CSRF token (via Auth extractor)
 * 3. Deletes session from database
 * 4. Returns cookie with Max-Age=0 to clear it from browser
 *
 * # Security
 *
 * This is a state-changing operation, so it requires CSRF protection. The session cookie
 * alone is not sufficient - the CSRF token must also be provided.
 *
 * # Example
 *
 * ```bash
 * curl -X POST http://localhost:3000/v1/auth/logout \
 * -H "X-CSRF-Token: {csrf_token_from_login}" \
 * -b cookies.txt
 * ```
 *
 * # Errors
 *
 * - 401 Unauthorized: Missing or invalid session cookie
 * - 403 Forbidden: Invalid CSRF token
 * - 500 Internal Server Error: Database failure
 */
export const authLogoutMutation = (options?: Partial<Options<AuthLogoutData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<AuthLogoutData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<AuthLogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authLogout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const authWhoamiQueryKey = (options?: Options<AuthWhoamiData>) => createQueryKey('authWhoami', options);

/**
 * Get information about the authenticated user.
 *
 * Returns the current user's profile information including ID, username, display name,
 * and email. Requires session cookie authentication (no CSRF token needed for GET requests).
 *
 * # Example
 *
 * ```bash
 * curl http://localhost:3000/v1/auth/me \
 * -b cookies.txt
 * ```
 *
 * # Response
 *
 * ```json
 * {
 * "id": "user_object_id",
 * "username": "admin",
 * "display_name": "Administrator",
 * "email": "admin@example.com"
 * }
 * ```
 *
 * # Errors
 *
 * - 401 Unauthorized: Missing or invalid session cookie
 * - 404 Not Found: User no longer exists in database (stale session)
 * - 500 Internal Server Error: Database failure
 */
export const authWhoamiOptions = (options?: Options<AuthWhoamiData>) => queryOptions<AuthWhoamiResponse, AxiosError<DefaultError>, AuthWhoamiResponse, ReturnType<typeof authWhoamiQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await authWhoami({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: authWhoamiQueryKey(options)
});

export const listCasQueryKey = (options?: Options<ListCasData>) => createQueryKey('listCas', options);

export const listCasOptions = (options?: Options<ListCasData>) => queryOptions<ListCasResponse, AxiosError<DefaultError>, ListCasResponse, ReturnType<typeof listCasQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listCas({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listCasQueryKey(options)
});

/**
 * Generate a new self-signed Ed25519 CA certificate and store it.
 */
export const generateCaMutation = (options?: Partial<Options<GenerateCaData>>): UseMutationOptions<GenerateCaResponse, AxiosError<DefaultError>, Options<GenerateCaData>> => {
    const mutationOptions: UseMutationOptions<GenerateCaResponse, AxiosError<DefaultError>, Options<GenerateCaData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await generateCa({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Import an existing CA certificate and private key.
 */
export const importCaMutation = (options?: Partial<Options<ImportCaData>>): UseMutationOptions<ImportCaResponse, AxiosError<DefaultError>, Options<ImportCaData>> => {
    const mutationOptions: UseMutationOptions<ImportCaResponse, AxiosError<DefaultError>, Options<ImportCaData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await importCa({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteCaMutation = (options?: Partial<Options<DeleteCaData>>): UseMutationOptions<DeleteCaResponse, AxiosError<DefaultError>, Options<DeleteCaData>> => {
    const mutationOptions: UseMutationOptions<DeleteCaResponse, AxiosError<DefaultError>, Options<DeleteCaData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteCa({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getCaQueryKey = (options: Options<GetCaData>) => createQueryKey('getCa', options);

export const getCaOptions = (options: Options<GetCaData>) => queryOptions<GetCaResponse, AxiosError<DefaultError>, GetCaResponse, ReturnType<typeof getCaQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCa({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCaQueryKey(options)
});

export const listHostsQueryKey = (options?: Options<ListHostsData>) => createQueryKey('listHosts', options);

export const listHostsOptions = (options?: Options<ListHostsData>) => queryOptions<ListHostsResponse, AxiosError<DefaultError>, ListHostsResponse, ReturnType<typeof listHostsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listHosts({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listHostsQueryKey(options)
});

export const getHostQueryKey = (options: Options<GetHostData>) => createQueryKey('getHost', options);

export const getHostOptions = (options: Options<GetHostData>) => queryOptions<GetHostResponse, AxiosError<DefaultError>, GetHostResponse, ReturnType<typeof getHostQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getHost({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getHostQueryKey(options)
});
