// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { authLogin, authLogout, authWhoami, getHost, listHosts, type Options } from '../sdk.gen';
import type { AuthLoginData, AuthLoginResponse2, AuthLogoutData, AuthWhoamiData, AuthWhoamiResponse, GetHostData, GetHostResponse, ListHostsData, ListHostsResponse } from '../types.gen';

/**
 * Authenticate user and create session.
 *
 * This endpoint validates user credentials and creates a new session stored in the database.
 * On success, it returns a session cookie and a CSRF token.
 *
 * # Flow
 *
 * 1. Validates username/password against database
 * 2. Generates unique session_id (ULID) and csrf_token (32 random chars)
 * 3. Creates session in database with 30-day TTL
 * 4. Signs session_id with Ed25519 key
 * 5. Returns signed token in `lucid_session` cookie + CSRF token in response body
 *
 * # Cookie Format
 *
 * - Name: `lucid_session`
 * - Value: `{session_id}.{ed25519_signature}`
 * - Flags: HttpOnly, SameSite=Lax, Path=/, Max-Age=2592000 (30 days)
 * - Secure: Only set when `public_url` starts with https://
 *
 * # CSRF Token
 *
 * The CSRF token must be stored by the client (e.g., in memory or localStorage) and sent
 * in the `X-CSRF-Token` header for all state-changing requests (POST, PUT, DELETE).
 *
 * # Example
 *
 * ```bash
 * curl -X POST http://localhost:3000/v1/auth/login \
 * -H "Content-Type: application/json" \
 * -d '{"username": "admin", "password": "secret"}' \
 * -c cookies.txt
 * ```
 *
 * # Errors
 *
 * - 401 Unauthorized: Invalid username or password
 * - 500 Internal Server Error: Database or signing failure
 */
export const authLoginMutation = (options?: Partial<Options<AuthLoginData>>): UseMutationOptions<AuthLoginResponse2, AxiosError<DefaultError>, Options<AuthLoginData>> => {
    const mutationOptions: UseMutationOptions<AuthLoginResponse2, AxiosError<DefaultError>, Options<AuthLoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authLogin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * End the current session.
 *
 * This endpoint deletes the user's session from the database and clears the session cookie.
 * Requires both session cookie authentication AND the CSRF token.
 *
 * # Flow
 *
 * 1. Extracts and verifies session cookie from request
 * 2. Validates CSRF token (via Auth extractor)
 * 3. Deletes session from database
 * 4. Returns cookie with Max-Age=0 to clear it from browser
 *
 * # Security
 *
 * This is a state-changing operation, so it requires CSRF protection. The session cookie
 * alone is not sufficient - the CSRF token must also be provided.
 *
 * # Example
 *
 * ```bash
 * curl -X POST http://localhost:3000/v1/auth/logout \
 * -H "X-CSRF-Token: {csrf_token_from_login}" \
 * -b cookies.txt
 * ```
 *
 * # Errors
 *
 * - 401 Unauthorized: Missing or invalid session cookie
 * - 403 Forbidden: Invalid CSRF token
 * - 500 Internal Server Error: Database failure
 */
export const authLogoutMutation = (options?: Partial<Options<AuthLogoutData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<AuthLogoutData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<AuthLogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authLogout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const authWhoamiQueryKey = (options?: Options<AuthWhoamiData>) => createQueryKey('authWhoami', options);

/**
 * Get information about the authenticated user.
 *
 * Returns the current user's profile information including ID, username, display name,
 * and email. Requires session cookie authentication (no CSRF token needed for GET requests).
 *
 * # Example
 *
 * ```bash
 * curl http://localhost:3000/v1/auth/me \
 * -b cookies.txt
 * ```
 *
 * # Response
 *
 * ```json
 * {
 * "id": "user_object_id",
 * "username": "admin",
 * "display_name": "Administrator",
 * "email": "admin@example.com"
 * }
 * ```
 *
 * # Errors
 *
 * - 401 Unauthorized: Missing or invalid session cookie
 * - 404 Not Found: User no longer exists in database (stale session)
 * - 500 Internal Server Error: Database failure
 */
export const authWhoamiOptions = (options?: Options<AuthWhoamiData>) => queryOptions<AuthWhoamiResponse, AxiosError<DefaultError>, AuthWhoamiResponse, ReturnType<typeof authWhoamiQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await authWhoami({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: authWhoamiQueryKey(options)
});

export const listHostsQueryKey = (options?: Options<ListHostsData>) => createQueryKey('listHosts', options);

export const listHostsOptions = (options?: Options<ListHostsData>) => queryOptions<ListHostsResponse, AxiosError<DefaultError>, ListHostsResponse, ReturnType<typeof listHostsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listHosts({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listHostsQueryKey(options)
});

export const getHostQueryKey = (options: Options<GetHostData>) => createQueryKey('getHost', options);

export const getHostOptions = (options: Options<GetHostData>) => queryOptions<GetHostResponse, AxiosError<DefaultError>, GetHostResponse, ReturnType<typeof getHostQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getHost({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getHostQueryKey(options)
});
