// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { authLogin, authLogout, authWhoami, getHost, listHosts, type Options } from '../sdk.gen';
import type { AuthLoginData, AuthLoginResponse2, AuthLogoutData, AuthWhoamiData, AuthWhoamiResponse, GetHostData, GetHostResponse, ListHostsData, ListHostsResponse } from '../types.gen';

export const authLoginMutation = (options?: Partial<Options<AuthLoginData>>): UseMutationOptions<AuthLoginResponse2, AxiosError<DefaultError>, Options<AuthLoginData>> => {
    const mutationOptions: UseMutationOptions<AuthLoginResponse2, AxiosError<DefaultError>, Options<AuthLoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authLogin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const authLogoutMutation = (options?: Partial<Options<AuthLogoutData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<AuthLogoutData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<AuthLogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authLogout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const authWhoamiQueryKey = (options?: Options<AuthWhoamiData>) => createQueryKey('authWhoami', options);

export const authWhoamiOptions = (options?: Options<AuthWhoamiData>) => queryOptions<AuthWhoamiResponse, AxiosError<DefaultError>, AuthWhoamiResponse, ReturnType<typeof authWhoamiQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await authWhoami({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: authWhoamiQueryKey(options)
});

export const listHostsQueryKey = (options?: Options<ListHostsData>) => createQueryKey('listHosts', options);

export const listHostsOptions = (options?: Options<ListHostsData>) => queryOptions<ListHostsResponse, AxiosError<DefaultError>, ListHostsResponse, ReturnType<typeof listHostsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listHosts({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listHostsQueryKey(options)
});

export const getHostQueryKey = (options: Options<GetHostData>) => createQueryKey('getHost', options);

export const getHostOptions = (options: Options<GetHostData>) => queryOptions<GetHostResponse, AxiosError<DefaultError>, GetHostResponse, ReturnType<typeof getHostQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getHost({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getHostQueryKey(options)
});
