/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConsoleRouteImport } from './routes/_console'
import { Route as ConsoleIndexRouteImport } from './routes/_console/index'
import { Route as authAuthRouteImport } from './routes/(auth)/_auth'
import { Route as ConsoleHostsIndexRouteImport } from './routes/_console/hosts/index'
import { Route as ConsoleActivationKeysIndexRouteImport } from './routes/_console/activation-keys/index'
import { Route as ConsoleAdminCertificateAuthoritiesIndexRouteImport } from './routes/_console/admin/certificate-authorities/index'
import { Route as authAuthAuthLoginRouteImport } from './routes/(auth)/_auth/auth.login'

const ConsoleRoute = ConsoleRouteImport.update({
  id: '/_console',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const authAuthRoute = authAuthRouteImport.update({
  id: '/(auth)/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleHostsIndexRoute = ConsoleHostsIndexRouteImport.update({
  id: '/hosts/',
  path: '/hosts/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleActivationKeysIndexRoute =
  ConsoleActivationKeysIndexRouteImport.update({
    id: '/activation-keys/',
    path: '/activation-keys/',
    getParentRoute: () => ConsoleRoute,
  } as any)
const ConsoleAdminCertificateAuthoritiesIndexRoute =
  ConsoleAdminCertificateAuthoritiesIndexRouteImport.update({
    id: '/admin/certificate-authorities/',
    path: '/admin/certificate-authorities/',
    getParentRoute: () => ConsoleRoute,
  } as any)
const authAuthAuthLoginRoute = authAuthAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => authAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ConsoleIndexRoute
  '/activation-keys/': typeof ConsoleActivationKeysIndexRoute
  '/hosts/': typeof ConsoleHostsIndexRoute
  '/auth/login': typeof authAuthAuthLoginRoute
  '/admin/certificate-authorities/': typeof ConsoleAdminCertificateAuthoritiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ConsoleIndexRoute
  '/activation-keys': typeof ConsoleActivationKeysIndexRoute
  '/hosts': typeof ConsoleHostsIndexRoute
  '/auth/login': typeof authAuthAuthLoginRoute
  '/admin/certificate-authorities': typeof ConsoleAdminCertificateAuthoritiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_console': typeof ConsoleRouteWithChildren
  '/(auth)/_auth': typeof authAuthRouteWithChildren
  '/_console/': typeof ConsoleIndexRoute
  '/_console/activation-keys/': typeof ConsoleActivationKeysIndexRoute
  '/_console/hosts/': typeof ConsoleHostsIndexRoute
  '/(auth)/_auth/auth/login': typeof authAuthAuthLoginRoute
  '/_console/admin/certificate-authorities/': typeof ConsoleAdminCertificateAuthoritiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activation-keys/'
    | '/hosts/'
    | '/auth/login'
    | '/admin/certificate-authorities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activation-keys'
    | '/hosts'
    | '/auth/login'
    | '/admin/certificate-authorities'
  id:
    | '__root__'
    | '/_console'
    | '/(auth)/_auth'
    | '/_console/'
    | '/_console/activation-keys/'
    | '/_console/hosts/'
    | '/(auth)/_auth/auth/login'
    | '/_console/admin/certificate-authorities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ConsoleRoute: typeof ConsoleRouteWithChildren
  authAuthRoute: typeof authAuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_console': {
      id: '/_console'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/': {
      id: '/_console/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/(auth)/_auth': {
      id: '/(auth)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/hosts/': {
      id: '/_console/hosts/'
      path: '/hosts'
      fullPath: '/hosts/'
      preLoaderRoute: typeof ConsoleHostsIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/activation-keys/': {
      id: '/_console/activation-keys/'
      path: '/activation-keys'
      fullPath: '/activation-keys/'
      preLoaderRoute: typeof ConsoleActivationKeysIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/admin/certificate-authorities/': {
      id: '/_console/admin/certificate-authorities/'
      path: '/admin/certificate-authorities'
      fullPath: '/admin/certificate-authorities/'
      preLoaderRoute: typeof ConsoleAdminCertificateAuthoritiesIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/(auth)/_auth/auth/login': {
      id: '/(auth)/_auth/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof authAuthAuthLoginRouteImport
      parentRoute: typeof authAuthRoute
    }
  }
}

interface ConsoleRouteChildren {
  ConsoleIndexRoute: typeof ConsoleIndexRoute
  ConsoleActivationKeysIndexRoute: typeof ConsoleActivationKeysIndexRoute
  ConsoleHostsIndexRoute: typeof ConsoleHostsIndexRoute
  ConsoleAdminCertificateAuthoritiesIndexRoute: typeof ConsoleAdminCertificateAuthoritiesIndexRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleIndexRoute: ConsoleIndexRoute,
  ConsoleActivationKeysIndexRoute: ConsoleActivationKeysIndexRoute,
  ConsoleHostsIndexRoute: ConsoleHostsIndexRoute,
  ConsoleAdminCertificateAuthoritiesIndexRoute:
    ConsoleAdminCertificateAuthoritiesIndexRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

interface authAuthRouteChildren {
  authAuthAuthLoginRoute: typeof authAuthAuthLoginRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authAuthAuthLoginRoute: authAuthAuthLoginRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ConsoleRoute: ConsoleRouteWithChildren,
  authAuthRoute: authAuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
