###
# Lucid example configuration file
###

# The format to emit logs in
# Supported values: json, logfmt or pretty
log_format = "json"

# The minimum log level to emit logs at
# Supported values: trace, debug, info, warn, error
log_level = "info"

# Public url of the API service. This should include the protocol, host and port
# that a user would use to connect to the server on.
public_url = ""

# Port for the server to run on. This does not have to match the public_url
# (i.e. in the case that the server is running behind a proxy)
server_port = 8080

# Full URL of the Postgres database to connect to.
database_url = "postgres://<user>:<password>@<host>:<port>/<database>"
